# Xephon-K benchmark config example
log:
  level: info
  color: true
  source: false
# local/remote
# TODO: remote is not supported, but we should, and it should also be able to spawn the needed resources
mode: local
loader:
  target: xephonk
  # discard | basic
  reporter: basic
  # limitBy: time | points
  limitBy: time
  points: 1000000
  series: 100
  time: 10
  workerNum: 10
  workerTimeout: 30
#  TODO: qps is not supported
#  qps: -1
generator:
  # TODO: minimal uint is 1s
  timeInterval: 1
  timeNoise: false
#  int:
#    max: 10
#    min: 1
#  double:
#    max: 1.0
#    min: 2.2
  pointsPerSeries: 100
  numSeries: 10
  #  int: 0.1
  #  double: 0.9
#reporter:
  # report to tsdb
  # aggregation interval etc.
#  interval:
targets:
  influxdb:
    host: localhost
    port: 8086
    url: write?db=sb
    timeout: 30
  xephonk:
    host: localhost
    port: 2333
    url: write
    timeout: 30
  kairosdb:
    host: localhost
    port: 8080
    url: api/v1/datapoints
    timeout: 30

