version: '2'
services:
  kairosdb:
    container_name: xephonhq-kairosdb-cp
    hostname: kairosdb
    build: ./node
    ports:
      # Web UI and HTTP API
      - "8080:8080"
    # NOTE: depends_on is not enough, wait-for-it is used in kairosdb.sh
    # in order to let cassandra running before KairosDB start
    depends_on:
      - kairosdbcassandra
    links:
      - kairosdbcassandra
  kairosdbcassandra:
    image: cassandra:2.2
    environment:
      - CASSANDRA_START_RPC=true
